name: terraform-apply
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
  - cron: 0 0 * * *

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
      GITHUB_TOKEN: ${{ secrets.WRITABLE_GITHUB_TOKEN }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform command
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform fmt
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init
    
    - name: Prepare execution
      run: .github/workflows/prepare.sh

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Upload tmp folder
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: repodatas
        path: |
          tmp/**
          repos.auto.tfvars.json
