name: terraform-apply
on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
  - cron: 0 0 * * *

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
      GITHUB_TOKEN: ${{ secrets.WRITABLE_GITHUB_TOKEN }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform command
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_wrapper: false

    - name: Terraform fmt
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init

    - name: Prepare execution
      run: ./prepare.sh

    - name: Encrypt repodata files
      run: |
        terraform state pull > terraform.tfstate
        tar -cf - tmp terraform.tfstate repos.auto.tfvars.json \
        | openssl enc -aes-256-cbc -salt -out archive.tar.enc -pass env:PASSWORD
      env:
        PASSWORD: ${{ secrets.PASSWORD }}

    - name: Upload repodatas to artifact
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: repodatas
        path: archive.tar.enc
