name: terraform-apply
on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
  - cron: 0 0 * * *

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform command
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Terraform fmt
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init

    - name: Get prev run's ID
      id: prev-run
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        PREV_RUN_ID=$(gh run list --limit 100 \
          --json databaseId,status,conclusion,name \
          | jq -r "[.[] | select(.name==\"${{ github.workflow }}\" and .conclusion == \"success\") | .][0].databaseId"
        )
        echo "id=${PREV_RUN_ID}" >> $GITHUB_OUTPUT

    - name: Download repodata files
      uses: actions/download-artifact@v4
      with:
        name: repodatas
        github-token: ${{ github.token }}
        run-id: ${{ steps.prev-run.outputs.id }}

    - name: Decrypt repodata files
      run: |
        openssl enc -d -aes256 -pbkdf2 -md sha-256 -in archive.tar.enc -pass env:PASSWORD \
        | tar -xf -
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
    
    - name: Get GitHub App Token(for all repositories)
      uses: actions/create-github-app-token@v1
      id: github-app
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Prepare execution
      run: ./prepare.sh
      env:
        GH_TOKEN: ${{ steps.github-app.outputs.token }}
    
    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        GH_TOKEN: ${{ steps.github-app.outputs.token }}

    - name: Encrypt repodata files
      run: |
        tar -cf - tmp terraform.tfstate repos.auto.tfvars.json \
        | openssl enc -aes256 -pbkdf2 -md sha-256 -out archive.tar.enc -pass env:PASSWORD
      env:
        PASSWORD: ${{ secrets.PASSWORD }}

    - name: Upload repodatas to artifact
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: repodatas
        path: archive.tar.enc
