name: CI
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
  - cron: 0 0 * * *

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Setup Terraform command
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Get prev run's ID
      if: github.event_name != 'pull_request'
      id: prev-run
      run: |
        PREV_RUN_ID=$(gh run list --limit 100 --json databaseId,event,name,conclusion \
          | jq -r "[.[] | select(.name==\"${{ github.workflow }}\" and .event != \"pull_request\" and .conclusion == \"success\") | .][0].databaseId"
        )
        echo "id=${PREV_RUN_ID}" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Download tfstate files
      if: github.event_name != 'pull_request'
      uses: actions/download-artifact@v6
      with:
        name: tfstate
        github-token: ${{ github.token }}
        run-id: ${{ steps.prev-run.outputs.id }}

    - name: Decrypt tfstate files
      if: github.event_name != 'pull_request'
      run: |
        openssl enc -d -aes256 -pbkdf2 -md sha-256 \
          -in terraform.tfstate.enc -out terraform.tfstate -pass env:PASSWORD
      env:
        PASSWORD: ${{ secrets.PASSWORD }}

    - name: Terraform fmt
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init

    - name: TF validate
      if: github.event_name == 'pull_request'
      run: terraform validate

    - name: Get GitHub App Token(for all repositories)
      if: github.event_name != 'pull_request'
      uses: actions/create-github-app-token@v2
      id: github-app
      with:
        app-id: ${{ vars.ADMIN_BOT_ID }}
        private-key: ${{ secrets.ADMIN_BOT_PRIVATEKEY }}
        owner: ${{ github.repository_owner }}

    - name: Prepare execution
      if: github.event_name != 'pull_request'
      run: ./setup.sh
      env:
        GITHUB_TOKEN: ${{ steps.github-app.outputs.token }}
        GITHUB_OWNER: ${{ github.repository_owner }}
        TF_VAR_GITHUB_OWNER: ${{ github.repository_owner }}
        TF_VAR_BUMP_BOT_PRIVATEKEY: ${{ secrets.BUMP_BOT_PRIVATEKEY }}
        TF_VAR_AUTOMERGE_BOT_PRIVATEKEY: ${{ secrets.AUTOMERGE_BOT_PRIVATEKEY }}
        TF_VAR_DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        TF_VAR_DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: TF apply
      if: github.event_name != 'pull_request'
      run: terraform apply -auto-approve
      env:
        GITHUB_TOKEN: ${{ steps.github-app.outputs.token }}
        GITHUB_OWNER: ${{ github.repository_owner }}
        TF_VAR_GITHUB_OWNER: ${{ github.repository_owner }}
        TF_VAR_BUMP_BOT_PRIVATEKEY: ${{ secrets.BUMP_BOT_PRIVATEKEY }}
        TF_VAR_AUTOMERGE_BOT_PRIVATEKEY: ${{ secrets.AUTOMERGE_BOT_PRIVATEKEY }}
        TF_VAR_DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        TF_VAR_DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Encrypt tfstate files
      if: ${{ github.event_name != 'pull_request' && always() }}
      run: |
        openssl enc -aes256 -pbkdf2 -md sha-256 \
          -in terraform.tfstate -out terraform.tfstate.enc -pass env:PASSWORD
      env:
        PASSWORD: ${{ secrets.PASSWORD }}

    - name: Upload tfstate to artifact
      if: ${{ github.event_name != 'pull_request' && always() }}
      uses: actions/upload-artifact@v5
      with:
        name: tfstate
        path: terraform.tfstate.enc

    - name: Encrypt repodata files
      if: ${{ github.event_name != 'pull_request' && always() }}
      run: |
        tar -cf - tmp repos.auto.tfvars.json \
        | openssl enc -aes256 -pbkdf2 -md sha-256 \
          -out archive.tar.enc -pass env:PASSWORD
      env:
        PASSWORD: ${{ secrets.PASSWORD }}

    - name: Upload repodatas to artifact
      if: ${{ github.event_name != 'pull_request' && always() }}
      uses: actions/upload-artifact@v5
      with:
        name: repodatas
        path: archive.tar.enc
