name: terraform-plan
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform command
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform fmt
      run: terraform fmt -check

    - name: Terraform Init
      env:
        TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
        TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
      run: terraform init
    
    - name: Prepare execution
      env:
        GITHUB_TOKEN: ${{ secrets.WRITABLE_GITHUB_TOKEN }}
      run: .github/workflows/prepare.sh
    
    - name: Terraform Plan
      run: terraform plan
