name: terraform-plan
on:
  workflow_dispatch:
  pull_request_target:
    branches: [ "main" ]

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
      GITHUB_TOKEN: ${{ secrets.WRITABLE_GITHUB_TOKEN }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform command
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_wrapper: false

    - name: Terraform fmt
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init

    - name: Prepare execution
      run: .github/workflows/prepare.sh

    - name: Terraform Plan
      run: terraform plan

    - name: Upload tmp folder
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: repodatas
        path: |
          tmp/**
          repos.auto.tfvars.json
